#!/bin/sh
# Code generated by volt v0.2.0 — DO NOT EDIT.
#
# Regenerate:  volt gen install cli/cmd/ds
# To change:   edit .volt.yml, or the template in volt itself — edits here are lost.
# volt:hash 765d497ff15f
# ds installer for macOS / Linux.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/ubgo/docsync/main/install.sh | sh
#   curl -fsSL https://raw.githubusercontent.com/ubgo/docsync/main/install.sh | VERSION=v1.2.0 sh               # pin a version
#   curl -fsSL https://raw.githubusercontent.com/ubgo/docsync/main/install.sh | INSTALL_DIR=$HOME/.local/bin sh  # no sudo needed
set -eu

REPO="ubgo/docsync"
BINARY="ds"
# Companion programs shipped in the same archive and installed beside
# ${BINARY}; empty when there are none.
EXTRA_BINARIES="ds-resolve-aws ds-resolve-env ds-resolve-gcp ds-resolve-github ds-resolve-onepassword ds-resolve-vault"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
VERSION="${VERSION:-}"
# The release-tag prefix of this CLI's stream: empty when the CLI is the repo
# root (tags v1.2.0), "<binary>/" when it lives in a subdirectory (tags
# <binary>/v1.2.0). A VERSION given with the prefix is accepted too.
TAG_PREFIX="ds/"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
case "$ARCH" in
  x86_64|amd64) ARCH="amd64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac
case "$OS" in
  linux|darwin) ;;
  *) echo "Unsupported OS: $OS (use install.ps1 on Windows)" >&2; exit 1 ;;
esac

if [ -n "$VERSION" ]; then
  VERSION=${VERSION#"$TAG_PREFIX"}
elif [ -n "$TAG_PREFIX" ]; then
  # "latest" is repo-global: in a repo with several release streams it is
  # whichever was published last, possibly one with no binaries. So list this
  # stream's tags instead; git ls-remote has no API rate limit.
  command -v git >/dev/null 2>&1 || { echo "git is needed to find the newest ${BINARY} release — or pass VERSION=vX.Y.Z" >&2; exit 1; }
  VERSION=$(git ls-remote --tags --refs "https://github.com/ubgo/docsync.git" "${TAG_PREFIX}v*" 2>/dev/null \
    | sed "s|.*refs/tags/${TAG_PREFIX}v||" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
    | sort -t. -k1,1n -k2,2n -k3,3n | tail -n1 | sed 's/^/v/')
  [ -n "$VERSION" ] || { echo "no ${TAG_PREFIX}v* release found in ${REPO} — pass VERSION=vX.Y.Z" >&2; exit 1; }
fi

if [ -n "$VERSION" ]; then
  TAG="${TAG_PREFIX}${VERSION}"
  BASE="https://github.com/ubgo/docsync/releases/download/${TAG}"
else
  # /releases/latest/download/ is a redirect with NO rate limit; the JSON API
  # is limited to 60 anonymous requests/hour/IP and would 403 on shared IPs.
  BASE="https://github.com/ubgo/docsync/releases/latest/download"
  # A forge with no latest-release redirect renders this empty — then a
  # version is required, loudly (FG-D4).
  [ -z "${BASE}" ] && { echo "this forge has no 'latest' redirect — pass a version: VERSION=vX.Y.Z" >&2; exit 1; }
  TAG="latest"
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
curl -fsSL -o "${tmp}/checksums.txt" "${BASE}/checksums.txt" || {
  echo "no release ${TAG} of ${BINARY} in ${REPO} (could not fetch ${BASE}/checksums.txt)" >&2; exit 1; }

# Asset names mirror volt's platform.AssetName — generated from the same
# constants, so they cannot drift from what the build produced. The asset is
# read from checksums.txt, which lists exactly what the release holds, so a
# platform the release does not build is reported as such rather than as a
# failed download.
if [ "$TAG" = "latest" ]; then
  ASSET=$(awk '{print $2}' "${tmp}/checksums.txt" | grep "_${OS}_${ARCH}\.tar\.gz$" | head -n1)
else
  ASSET="${BINARY}_${VERSION}_${OS}_${ARCH}.tar.gz"
  awk '{print $2}' "${tmp}/checksums.txt" | grep -qx "$ASSET" || ASSET=""
fi
[ -n "$ASSET" ] || { echo "release ${TAG} of ${REPO} has no ${OS}/${ARCH} build of ${BINARY}" >&2; exit 1; }

echo "Downloading ${ASSET} from ${REPO} (${TAG})..."
curl -fsSL -o "${tmp}/${ASSET}" "${BASE}/${ASSET}"

# Verify BEFORE installing — never pipe an unverified binary into PATH.
# sha256sum is coreutils; stock macOS ships only shasum — support both.
if command -v sha256sum >/dev/null 2>&1; then
  SUMCHECK="sha256sum -c -"
else
  SUMCHECK="shasum -a 256 -c -"
fi
(cd "$tmp" && grep " ${ASSET}\$" checksums.txt | $SUMCHECK >/dev/null) || {
  echo "checksum verification FAILED for ${ASSET} — refusing to install" >&2; exit 1; }

tar xzf "${tmp}/${ASSET}" -C "$tmp"
[ -f "${tmp}/${BINARY}" ] || { echo "${BINARY} not found in archive" >&2; exit 1; }

if [ -x "${INSTALL_DIR}/${BINARY}" ]; then
  echo "Replacing $("${INSTALL_DIR}/${BINARY}" --version 2>/dev/null || echo "existing install")"
fi
mkdir -p "$INSTALL_DIR" 2>/dev/null || true
if [ -w "$INSTALL_DIR" ]; then
  MV="mv"
elif command -v sudo >/dev/null 2>&1; then
  MV="sudo mv"
else
  echo "${INSTALL_DIR} is not writable and sudo is unavailable." >&2
  echo "Re-run with INSTALL_DIR set to a writable directory, e.g.:" >&2
  echo "  curl -fsSL https://raw.githubusercontent.com/ubgo/docsync/main/install.sh | INSTALL_DIR=\$HOME/.local/bin sh" >&2
  exit 1
fi
chmod +x "${tmp}/${BINARY}"
$MV "${tmp}/${BINARY}" "${INSTALL_DIR}/${BINARY}"
INSTALLED="${BINARY}"
for extra in $EXTRA_BINARIES; do
  # A release older than the companion may not carry it: say so, keep going.
  if [ -f "${tmp}/${extra}" ]; then
    chmod +x "${tmp}/${extra}"
    $MV "${tmp}/${extra}" "${INSTALL_DIR}/${extra}"
    INSTALLED="${INSTALLED} ${extra}"
  else
    echo "NOTE: ${extra} is not in release ${TAG}; skipped." >&2
  fi
done

case ":$PATH:" in
  *":${INSTALL_DIR}:"*) ;;
  *) echo "NOTE: ${INSTALL_DIR} is not on your PATH." >&2 ;;
esac
echo "Installed ${INSTALLED} to ${INSTALL_DIR}"
